(define (problem p8) 
(:domain blocksworld)
(:objects  AMARILLO  ROJO  VERDE  AZUL )
(:init (onTable AMARILLO) (clear AMARILLO) (equal AMARILLO AMARILLO) 
(onTable ROJO) (clear ROJO) (equal ROJO ROJO) 
(onTable VERDE) (clear VERDE) (equal VERDE VERDE) 
(onTable AZUL) (clear AZUL) (equal AZUL AZUL) 
)
(:goal (and (on ROJO AMARILLO)(on VERDE ROJO)(on AZUL VERDE))))