(define (problem p8) 
(:domain blocksworld)
(:objects  ROJO  VERDE )
(:init (onTable ROJO) (clear ROJO) (equal ROJO ROJO) 
(onTable VERDE) (clear VERDE) (equal VERDE VERDE) 
)
(:goal (and (on VERDE ROJO))))